name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        with:
          github_user_name: Sreyoshi244
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push the snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
